version: 1
labels:
- label: "feature"
  title: "^(feat|Feat).*"
- label: "feature"
  branch: "^(feat|Feat).*"
- label: "fix"
  title: "^(fix|Fix).*"
- label: "fix"
  branch: "^(fix|Fix).*"
- label: "refactor"
  branch: "^(refactor|Refactor).*"
- label: "refactor"
  title: "^(refactor|Refactor).*"
- label: "hotfix"
  branch: "^(hotfix|Hotfix).*"
- label: "hotfix"
  title: "^(hotfix|Hotfix).*"
