name: Label PRs

on:
- pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ok
      run: echo ${{ secrets.GITHUB_TOKEN }}
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
