name: Tests

on:
  pull_request:
    branches: 
      - main
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  # chromatic-deployment:
  #   runs-on: ubuntu-latest
  #   name: Deploy to Chromaitc
  #   if: github.event.pull_request.draft == false
  #   env:    
  #     NODE_OPTIONS: --max-old-space-size=6144
  #   steps:
  #     - name: Labeled to skip-changelog
  #       id: haslabel
  #       uses: DanielTamkin/HasLabel@v1.0.4
  #       with:
  #         contains: 'skip-changelog'

  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0 # 👈 Required to retrieve git history

  #     - name: Get yarn cache directory path
  #       id: yarn-cache-dir-path
  #       run: echo "::set-output name=dir::$(yarn cache dir)" 

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14

  #     - uses: actions/cache@v2
  #       id: yarn-cache
  #       with:
  #         path: |
  #           **/node_modules
  #           ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-

  #     - name: Install packages
  #       run: yarn install --frozen-lockfile

  #     - name: Publish to Chromatic
  #       if: steps.haslabel.outputs.labeled-skip-changelog != 'true'
  #       uses: chromaui/action@v1
  #       with:
  #         projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  #         exitOnceUploaded: true
  #         onlyChanged: true

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    env:    
      NODE_OPTIONS: --max-old-space-size=6144
    steps:      
      - name: placeholder
        run: echo "test coming soon" 
        

      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)" 

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - uses: actions/cache@v2
      #   id: yarn-cache
      #   with:
      #     path: |
      #       **/node_modules
      #       ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # - name: Install packages
      #   run: yarn install --frozen-lockfile

      # - name: Run tests
      #   run: yarn test:unit
